//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD.Peliculas_WS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pelicula
    {
        public System.Guid id { get; set; }
        public string Titulo { get; set; }
        public string FechaEstreno { get; set; }
        public string Genero { get; set; }
    }
}
